### ISSUE TITLE
Blog一覧ページのbodyの表示修正

### ISSUE THREAD

**Issue by tocchi-739** [junji-s/qin-portfolio-1-h#1]
■該当のページ
https://qin-portfolio-1-h.vercel.app/
https://qin-portfolio-1-h.vercel.app/blog

■修正点
bodyの表示でタグが含まれてしまっている
例：`<h2><p>`など

■該当ファイル
src/components/molecles/BlogLink.tsx

■参考
src/pages/blog/[id].tsx と同様にしたら良いかと思います

**Comment by junji-s** [comment]
これって、リッチエディタにすると、...にならなくなるんですが、トッチさんはできましたか？

**Comment by tocchi-739** [comment]
答えになっているかわかりませんが😅
自分はリッチエディタで表示はこんな感じです！
■表示
https://qin-team-dev.vercel.app/blogPage
■blogコンポーネント
https://github.com/tocchi-739/qin-team-dev/blob/main/src/components/Blog.jsx
