### ISSUE TITLE
フッターのスマホ表示

### ISSUE THREAD

**Issue by tocchi-739** [junji-s/qin-portfolio-1-h#2]
■修正点
私のスマホで表示した際に、以下のような感じで途中で折り返されてしまっている。
chromeのdevツールでは問題なさそうです。
![スクリーンショット 2022-08-31 18 11 10](https://user-images.githubusercontent.com/101105704/187644477-477730df-0c26-4f1c-8d5a-64bdc2ae602b.jpg)

Issue立てておきながらですが、、
CSSを見たのですが、気になる点はありませんでした。
可能であれば修正いただければと思います。

■参考
機種：IphoneSE2
アプリ：safari / Google

**Comment by junji-s** [comment]
実案件ではないからと、ブラウザチェック怠っていました。。。
ご指摘ありがとうございます！！

**Comment by tocchi-739** [comment]
細かい点失礼しました、！
